Create list of raindrops retreived from API
Supernovaxxx/showcase pull request #2
Opened 2023-10-01 19:20 UTC by julianastahelin

Raindrop API URL: https://developer.raindrop.io/

2023-10-02 14:17 UTC, artu-hnrq reviewed
Keep up the great work!

2023-10-03 20:24 UTC, artu-hnrq commented on components/core/references/card.tsx
> +import { Raindrop } from "./panel"
What is a Raindrop in panel?

2023-10-03 22:09 UTC, artu-hnrq commented on components/core/references/panel.tsx
> +import { ChevronLeft, ChevronRight } from "lucide-react"
Organize all icons to be imported from sabe module

2023-10-03 22:09 UTC, artu-hnrq commented on components/core/references/panel.tsx
> +export interface Raindrops {
Consider rename it to `CollectionRaindropsResponse` and move to Types

2023-10-05 15:02 UTC, artu-hnrq requested changes
We are almost there! Keep going!

2023-10-05 15:02 UTC, artu-hnrq commented on app/globals.css
> +.small-caps {
Consider use [tailwind arbitrary proprieties][1] in a component instead a css class

  [1]: https://tailwindcss.com/docs/adding-custom-styles#arbitrary-properties

2023-10-05 15:02 UTC, artu-hnrq commented on components/core/skills/badge-list.tsx
> +import { SkillBadge, ToggleSkill, SkillIsActive } from '@/components/core/skills'
Let's name boolean-return functions as questions, though `IsActiveSkill` seems better, I'd say

2023-10-05 15:02 UTC, artu-hnrq commented on components/site/icons/favicon.tsx
> +export function Favicon({domain}: {domain: string}) {
It can be slightly better

2023-10-06 17:54 UTC, julianastahelin commented on components/core/references/panel.tsx
> +import { ChevronLeft, ChevronRight } from "lucide-react"
ok! done

2023-10-06 17:55 UTC, julianastahelin commented on app/globals.css
> +.small-caps {
Good idea. Done

2023-10-06 17:56 UTC, julianastahelin commented on components/site/icons/favicon.tsx
> +export function Favicon({domain}: {domain: string}) {
Renamed it to ExternalDomainFavicon and refactored.

2023-10-07 16:31 UTC, artu-hnrq approved these changes

2023-10-07 16:34 UTC, merged